#!/bin/sh

# deployment script
DEPLOYDIR=~/apps/orsty

GIT_WORK_TREE ="$DEPLOYDIR" git checkout -f 

cd "$DEPLOYDIR"

forever stop server.js

npm install

forever start server.js

echo "All done ;)"


